site_name: 手册
repo_url: https://github.com/aminerdocs/docs
site_description: 贝格迈思数据库使用手册
copyright: Copyright © 2023 - 2024 贝格迈思（深圳）技术有限公司 粤ICP备17054434号-1
theme:
    custom_dir: material/overrides # 自定义文件夹
    name: material
    logo: assets/new-logo.png
    favicon: assets/favicon.png
    features:
        - announce.dismiss # 可以叉掉公告的功能
        - content.action.edit # 编辑按钮，似乎没啥用
        - content.action.view # 查看按钮，似乎没啥用
        - content.code.annotate # 代码注释，具体不清楚
        - content.code.copy # 复制代码按钮
        - content.code.select # 选择代码按钮
        # - content.tabs.link # 链接标签
        - content.tooltips # 不太清楚呢这个
        # - header.autohide # 自动隐藏header
        # - navigation.expand # 默认展开导航栏
        - navigation.footer # 底部导航栏
        - navigation.indexes # 索引按钮可以直接触发文件，而不是只能点击其下属选项浏览，这个功能可以给对应的section提供很好的预览和导航功能
        # - navigation.instant # 瞬间加载 最好注释掉，多语言切换这个会导致跳回首页
        - navigation.instant.prefetch # 预加载
        - navigation.instant.progress # 进度条
        - navigation.path # 导航路径， 目前好像没啥用
        # - navigation.prune # 只构建可见的页面
        - navigation.sections # 导航栏的section
        # - navigation.tabs # 顶级索引被作为tab
        - navigation.tabs.sticky # tab始终可见
        - navigation.top # 开启顶部导航栏
        - navigation.tracking # 导航栏跟踪
        - search.highlight # 搜索高亮
        - search.share # 搜索分享
        - search.suggest # 搜索建议
        - toc.follow # 目录跟踪-页面右侧的小目录
        # - toc.integrate # 目录跟踪集成到左侧大目录中
    palette:
        scheme: mo
        # primary: 'Light Blue'
        # accent: 'Light Blue'
    font:
        text: Roboto
        code: Roboto Mono
    language: zh # 一些提示性的文字会变成中文
    icon: 
        repo: fontawesome/brands/github #右上角图标
docs_dir: docs
site_dir: site
plugins:
    - tags
    - offline
    - search:
            separator: '[\s\-,:!=\[\]()"/]+|[，。！？…：“”‘’（）—【】《》]|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
    # - mike:
    #   alias_type: symlink
    #   redirect_template: null
    #   deploy_prefix: ''
    #   canonical_version: null
    #   version_selector: true
    #   css_dir: css
    #   javascript_dir: js

                        
    # - minify: # 压缩插件
    #   minify_html: true
    # - versioning:
    #   version_menu_number: 2  # 显示在侧边栏的版本数量
    #   version_dropdown: true  # 启用版本下拉菜单
    #   default_version: latest  # 默认显示最新版本
    #   previous_link: true  # 显示上一个版本链接
    #   next_link: true  # 显示下一个版本链接
extra_css:
    - stylesheets/extra.css
extra_javascript:
    - javascripts/extra.js
use_directory_urls: false
dev_addr: 0.0.0.0:8000
markdown_extensions:
    - abbr
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - md_in_html
    - pymdownx.arithmatex:  # latex支持
        generic: true
    - toc:
        permalink: true # 固定标题位置为当前位置
    - pymdownx.highlight: # 代码块高亮
        anchor_linenums: true
        linenums: true # 显示行号
        # auto_title: true # 显示编程语言名称
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences # 代码块高亮插件
    - meta # 支持Markdown文件上方自定义标题标签等
extra: 
    generator: false
    version:
        provider: mike
    social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/wcowin_
    - icon: fontawesome/brands/github
      link: https://github.com/Wcowin
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1407028951?spm_id_from=333.1007.0.0
    - icon: fontawesome/solid/paper-plane
      link: mailto:<1135801806@qq.com> #联系方式
  
    analytics: 
        provider: google
        property: G-XXXXXXXXXX # Google Analytics ID
        feedback:
        title: 此页面有帮助吗？
        ratings:
            - icon: material/thumb-up-outline
              name: This page was helpful
              data: 1
              note: >-
                谢谢你的反馈！
            - icon: material/thumb-down-outline
              name: This page could be improved
              data: 0
              note: >- 
                Thanks for your feedback! Help us improve this page by
                using our <a href="https://marketingplatform.google.com/about/analytics/" target="_blank" rel="noopener">feedback form</a>.
  
    consent:
        title: Cookie consent
        description: >- 
            我们也使用cookies来识别您的重复访问和偏好来衡量我们文档的有效性以及用户是否找到他们要找的东西。
            如果你同意,你可以帮助我们让我们的网站更好
# 配置版本选择器
versioning:
  enabled: true 
  versions:
    - label: 1.x
      directory: docs1  # 对应的文件夹名称
      name: 版本 1
    - label: 2.x
      directory: docs2
      name: 版本 2
  default: 2.x  # 默认版本

nav:
    -
        AiSQL简介: docs/01-AISQL简介.md
    -
        快速上手:
        -
            快速安装部署: docs/快速上手/快速安装部署.md
        -
            SQL基本操作: docs/快速上手/SQL基本操作.md
        -
            BCQL基本操作: docs/快速上手/BCQL基本操作.md
        -
            创建Java示例应用程序: docs/快速上手/创建Java示例应用.md
    - 
        应用开发:
        - 
            构建应用: 
            - 
                Java: docs/应用开发/构建应用/JAVA.md
            - 
                Go: docs/应用开发/构建应用/Go.md
            - 
                Python: docs/应用开发/构建应用/Python.md
            - 
                Node.js: docs/应用开发/构建应用/Node.js.md
            - 
                C: docs/应用开发/构建应用/C.md
            - 
                C++: docs/应用开发/构建应用/C++.md
            - 
                C#: docs/应用开发/构建应用/C#.md
            - 
                Ruby: docs/应用开发/构建应用/Ruby.md
            - 
                Rust: docs/应用开发/构建应用/Rust.md
            - 
                PHP: docs/应用开发/构建应用/PHP.md
        -
            构建全局应用程序: docs/应用开发/构建全局应用程序.md
        -
            构建多云应用程序: docs/应用开发/构建多云应用程序.md
        -
            常见模式: docs/应用开发/常见模式.md
        -
            学习应用程序开发:
            -
                数据建模: docs/应用开发/学习应用程序开发/数据建模.md
            -
                数据类型: docs/应用开发/学习应用程序开发/数据类型.md
            -
                SQL vs NoSQL: docs/应用开发/学习应用程序开发/SQLvsNoSQL.md
            -
                事务: docs/应用开发/学习应用程序开发/事务.md
            -
                文本搜索: docs/应用开发/学习应用程序开发/文本搜索.md
            -
                聚集: docs/应用开发/学习应用程序开发/聚集.md
            -
                批处理操作: docs/应用开发/学习应用程序开发/批处理操作.md
            -
                Date and time: docs/应用开发/学习应用程序开发/Date&Time.md
            -
                字符串和文本: docs/应用开发/学习应用程序开发/字符串和文本.md
            -
                数据过期的TTL: docs/应用开发/学习应用程序开发/数据过期的TTL.md
        -
            最佳实践: docs/应用开发/最佳实践.md
        -
            驱动与对象关系映射:
            -
                概述: docs/应用开发/驱动与对象关系映射/概述.md
            -
                BSQL智能驱动程序: docs/应用开发/驱动与对象关系映射/BSQL智能驱动程序.md
            -
                Java: docs/应用开发/驱动与对象关系映射/Java.md
            -
                Go: docs/应用开发/驱动与对象关系映射/Go.md
            -
                Python: docs/应用开发/驱动与对象关系映射/Python.md
            -
                Node.js: docs/应用开发/驱动与对象关系映射/Node.js.md
            -
                C: docs/应用开发/驱动与对象关系映射/C.md
            -
                C++: docs/应用开发/驱动与对象关系映射/C++.md
            -
                C#: docs/应用开发/驱动与对象关系映射/C#.md
            -
                Ruby: docs/应用开发/驱动与对象关系映射/Ruby.md
        -
            真实示例: docs/应用开发/真实示例.md
        -
            服务质量: docs/应用开发/服务质量.md
        -
            云原生开发: docs/应用开发/云原生开发.md
        -
            驱动和ORMs:
            -
                JDBC Drivers: docs/应用开发/驱动和ORMs/JDBC_Drivers.md
            -
                Node.js Drivers: docs/应用开发/驱动和ORMs/Node.js_Drivers.md
            -
                C# Drivers: docs/应用开发/驱动和ORMs/C#_Drivers.md
            -
                Go Drivers: docs/应用开发/驱动和ORMs/Go_Drivers.md
            -
                Python Drivers: docs/应用开发/驱动和ORMs/Python_Drivers.md
            -
                Rust Drivers: docs/应用开发/驱动和ORMs/Rust_Drivers.md
            -
                Client drivers for BSQL: docs/应用开发/驱动和ORMs/Client_drivers_for_BSQL.md
            -
                Client drivers for BCQL: docs/应用开发/驱动和ORMs/Client_drivers_for_BCQL.md
        -
            第三方工具: docs/应用开发/第三方工具.md
        -
            BSQL连接管理池: docs/应用开发/BSQL连接管理池.md
    -
        部署集群:
        -
            软硬件环境需求: docs/部署集群/软硬件环境需求.md
        -
            环境与系统配置检查: docs/部署集群/环境与系统配置检查.md
        -
            最小部署拓扑结构: docs/部署集群/最小部署拓扑结构.md
        -
            通过图形化界面部署: docs/部署集群/通过图形化界面部署.md
        -
            通过命令行部署: docs/部署集群/通过命令行部署.md
        -
            多数据中心部署: docs/部署集群/多数据中心部署.md
        -
            测试集群性能: docs/部署集群/测试集群性能.md
    -
        数据迁移: docs/05-数据迁移.md
    -
        管理数据库:
        -
            集群管理与监控: docs/管理数据库/集群管理与监控.md
        -
            更改集群配置: docs/管理数据库/更改集群配置.md
        -
            诊断报告: docs/管理数据库/诊断报告.md
        -
            安全权限:
            -
                安全检查清单: docs/管理数据库/安全权限/安全检查清单.md
            -
                启用认证: docs/管理数据库/安全权限/启用认证.md
            -
                认证方式: docs/管理数据库/安全权限/认证方式.md
            -
                基于角色的访问控制: docs/管理数据库/安全权限/基于角色的访问控制.md
            -
                传输加密: docs/管理数据库/安全权限/传输加密.md
            -
                静态加密: docs/管理数据库/安全权限/静态加密.md
            -
                列级加密: docs/管理数据库/安全权限/列级加密.md
            -
                审计: docs/管理数据库/安全权限/审计.md
        -
            备份修复:
            -
                备份和还原: docs/管理数据库/备份恢复/备份和还原.md
            -
                时间点回复: docs/管理数据库/备份恢复/时间点回复.md
        -
            监控指标: docs/管理数据库/监控指标.md
        -
            问题排查: docs/管理数据库/问题排查.md
        -
            性能调优:
            -
                引言: docs/管理数据库/性能调优/引言.md
            -
                收集查询统计信息: docs/管理数据库/性能调优/收集查询统计信息.md
            -
                查看实时查询: docs/管理数据库/性能调优/查看实时查询.md
            -
                查看已终止的查询: docs/管理数据库/性能调优/查看已终止的查询.md
            -
                查看复制状态: docs/管理数据库/性能调优/查看复制状态.md
            -
                查看索引创建状态: docs/管理数据库/性能调优/查看索引创建状态.md
            -
                查询计划: docs/管理数据库/性能调优/查询计划.md
            -
                优化BSQL查询: docs/管理数据库/性能调优/优化BSQL查询.md
        -
            高可用: docs/管理数据库/高可用.md
        -
            高扩展性: docs/管理数据库/高扩展性.md
        -
            多区域部署: docs/管理数据库/多区域部署.md
        -
            变更数据获取: docs/管理数据库/变更数据获取.md
        -
            升级部署: docs/管理数据库/升级部署.md
    -
        向量特性: docs/07-向量特性.md
    -
        AI特性:
        -
            概述: docs/AI特性/概述.md
        -
            架构: docs/AI特性/架构.md
        -
            基本原理: docs/AI特性/基本原理.md
        -
            详细功能说明:
            -
                表单数据服务模型: docs/AI特性/详细功能说明/表单数据服务模型.md
            -
                简洁数据服务模型: docs/AI特性/详细功能说明/简洁数据服务模型.md
            -
                算法扩展: docs/AI特性/详细功能说明/算法扩展.md
            -
                数据向量化和检索: docs/AI特性/详细功能说明/数据向量化和检索.md
            -
                大模型调用: docs/AI特性/详细功能说明/大模型调用.md
            -
                操作审计: docs/AI特性/详细功能说明/操作审计.md
            -
                备份和恢复: docs/AI特性/详细功能说明/备份和恢复.md
            -
                内置帮助服务: docs/AI特性/详细功能说明/内置帮助服务.md
    -
        参考:
        -
            架构:
            -
                设计目标: docs/架构/设计目标.md
            -
                基本概念: docs/架构/基本概念.md
            -
                核心功能: docs/架构/核心功能.md
            -
                分层架构: docs/架构/分层架构.md
            -
                查询层: docs/架构/查询层.md
            -
                CoreDB事务层:
                -
                    概述: docs/架构/CoreDB事务层/概述.md
                -
                    隔离级别: docs/架构/CoreDB事务层/隔离级别.md
                -
                    并发控制: docs/架构/CoreDB事务层/并发控制.md
                -
                    事务优先级: docs/架构/CoreDB事务层/事务优先级.md
                -
                    读已提交: docs/架构/CoreDB事务层/读已提交.md
                -
                    单行事务: docs/架构/CoreDB事务层/单行事务.md
                -
                    分布式事务: docs/架构/CoreDB事务层/分布式事务.md
                -
                    事务I/O路径: docs/架构/CoreDB事务层/事务IO路径.md
            -
                CoreDB分片层:
                -
                    哈希和范围分片: docs/架构/CoreDB分片层/哈希和范围分片.md
                -
                    Tile分裂: docs/架构/CoreDB分片层/Tile分裂.md
                -
                    Colocated tables: docs/架构/CoreDB分片层/Colocated_tables.md
            -
                CoreDB复制层:
                -
                    同步: docs/架构/CoreDB复制层/同步.md
                -
                    xDCR: docs/架构/CoreDB复制层/xDCR.md
                -
                    Read replicas: docs/架构/CoreDB复制层/Read_replicas.md
                -
                    Change data capture (CDC): docs/架构/CoreDB复制层/Change_data_capture(CDC).md
            -
                CoreDB存储层:
                -
                    持久化: docs/架构/CoreDB存储层/持久化.md
                -
                    性能: docs/架构/CoreDB存储层/性能.md
        -
            CLIs:
            -
                sqlsh:
                -
                    概述: docs/CLIs/sqlsh/概述.md
                -
                    基本语法: docs/CLIs/sqlsh/基本语法.md
                -
                    标志: docs/CLIs/sqlsh/标志.md
                -
                    变量: docs/CLIs/sqlsh/变量.md
                -
                    SQL中插入变量: docs/CLIs/sqlsh/SQL中插入变量.md
                -
                    环境变量: docs/CLIs/sqlsh/环境变量.md
                -
                    提示符: docs/CLIs/sqlsh/提示符.md
                -
                    文件: docs/CLIs/sqlsh/文件.md
                -
                    sqlsh元命令: docs/CLIs/sqlsh/sqlsh元命令.md
                -
                    模式(Pattern): docs/CLIs/sqlsh/模式(Pattern).md
                -
                    示例: docs/CLIs/sqlsh/示例.md
            -
                cqlsh: docs/CLIs/cqlsh.md
            -
                bm-admin:
                -
                    集群命令: docs/CLIs/bm-admin/集群命令.md
                -
                    表命令: docs/CLIs/bm-admin/表命令.md
                -
                    备份与快照命令: docs/CLIs/bm-admin/备份与快照命令.md
                -
                    多区，多地域部署命令: docs/CLIs/bm-admin/多区，多地域部署命令.md
                -
                    读副本部署命令: docs/CLIs/bm-admin/读副本部署命令.md
                -
                    安全命令: docs/CLIs/bm-admin/安全命令.md
                -
                    更改数据捕获命令: docs/CLIs/bm-admin/更改数据捕获命令.md
                -
                    xDCR复制命令: docs/CLIs/bm-admin/xDCR复制命令.md
                -
                    Decommissioning commands: docs/CLIs/bm-admin/Decommissioning_commands.md
                -
                    负载均衡命令: docs/CLIs/bm-admin/负载均衡命令.md
                -
                    更新BSQL系统目录: docs/CLIs/bm-admin/更新BSQL系统目录.md
            -
                dbserver-ctl: docs/CLIs/dbserver-ctl.md
            -
                bm-dump: docs/CLIs/bm-dump.md
            -
                bm-dumpall: docs/CLIs/bm-dumpall.md
            -
                bm-dev-ctl: docs/CLIs/bm-dev-ctl.md
        -
            配置:
            -
                bm-mserver: docs/配置/bm-mserver.md
            -
                bm-dbserver: docs/配置/bm-dbserver.md
            -
                bm-ctl: docs/配置/bm-ctl.md
            -
                默认端口: docs/配置/默认端口.md
        -
            BSQL:
            -
                数据类型:
                -
                    数组: docs/BSQL/数据类型/数组.md
                -
                    PL/pgSQL中的数组循环: docs/BSQL/数据类型/PLpgSQL中的数组循环.md
                -
                    使用DOMAIN值数组: docs/BSQL/数据类型/使用DOMAIN值数组.md
                -
                    数组函数和运算符: docs/BSQL/数据类型/数组函数和运算符.md
                -
                    Binary: docs/BSQL/数据类型/Binary.md
                -
                    Boolean: docs/BSQL/数据类型/Boolean.md
                -
                    Character: docs/BSQL/数据类型/Character.md
                -
                    date与time: docs/BSQL/数据类型/date与time.md
                -
                    json: docs/BSQL/数据类型/json.md
                -
                    Money: docs/BSQL/数据类型/Money.md
                -
                    数字类型: docs/BSQL/数据类型/数字类型.md
                -
                    范围类型: docs/BSQL/数据类型/范围类型.md
                -
                    Serial: docs/BSQL/数据类型/Serial.md
                -
                    UUID: docs/BSQL/数据类型/UUID.md
                -
                    枚举类型: docs/BSQL/数据类型/枚举类型.md
                -
                    几何类型: docs/BSQL/数据类型/几何类型.md
                -
                    网络地址类型: docs/BSQL/数据类型/网络地址类型.md
                -
                    位串类型: docs/BSQL/数据类型/位串类型.md
                -
                    文本搜索类型: docs/BSQL/数据类型/文本搜索类型.md
                -
                    域类型: docs/BSQL/数据类型/域类型.md
                -
                    伪类型: docs/BSQL/数据类型/伪类型.md
            -
                BSQL语言: docs/BSQL/BSQL语言.md
            -
                内置函数和运算符:
                -
                    逻辑操作符: docs/BSQL/内置函数和运算符/逻辑操作符.md
                -
                    比较函数和操作符: docs/BSQL/内置函数和运算符/比较函数和操作符.md
                -
                    数学函数和操作符: docs/BSQL/内置函数和运算符/数学函数和操作符.md
                -
                    数据类型格式化函数: docs/BSQL/内置函数和运算符/数据类型格式化函数.md
                -
                    模式匹配: docs/BSQL/内置函数和运算符/模式匹配.md
                -
                    条件表达式: docs/BSQL/内置函数和运算符/条件表达式.md
                -
                    子查询表达式: docs/BSQL/内置函数和运算符/子查询表达式.md
                -
                    行和数组比较: docs/BSQL/内置函数和运算符/行和数组比较.md
                -
                    集合返回函数: docs/BSQL/内置函数和运算符/集合返回函数.md
                -
                    窗口函数: docs/BSQL/内置函数和运算符/窗口函数.md
                -
                    聚集函数: docs/BSQL/内置函数和运算符/聚集函数.md
                -
                    系统信息函数和运算符: docs/BSQL/内置函数和运算符/系统信息函数和运算符.md
            -
                关键词: docs/BSQL/关键词.md
            -
                保留名称: docs/BSQL/保留名称.md
            -
                系统表/视图: docs/BSQL/系统表视图.md
        -
            BCQL:
            -
                数据类型: docs/BCQL/数据类型.md
            -
                函数和运算符: docs/BCQL/函数和运算符.md
            -
                BCQL语言: docs/BCQL/BCQL语言.md


                        
